version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    extra_hosts:
      - "ss-playground.test:127.0.0.1"
    hostname: ss-playground.test
    domainname: test
    ports:
      - 8000:80
    volumes: ['./:/var/www/html']
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ss_playground
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: ss_user
      MYSQL_PASSWORD: ss_pw
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '3333:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
volumes:
  php-apache-environment:
  db-data:
    driver: local
 